### ISSUE TITLE
useEffect vs useLayout Effect article

### ISSUE THREAD

**Issue by ooade** [kentcdodds/old-kentcdodds.com#101]
Nice one on the article. [Here](https://github.com/kentcdodds/kentcdodds.com/blob/master/content/blog/useeffect-vs-uselayouteffect/index.md), it did seem like there were 2 public effect hooks and 1 mystery hook. 

References to that:
- `All three of these`
- `some are more optimal than others`
- `and use the other two hooks`
- `the difference between the other two`

I wanted to edit and send in a PR, but I can't write like you :sweat_smile:

**Comment by kentcdodds** [comment]
Fixed! Thank you!

**Comment by kentcdodds** [comment]
There used to be three hooks for effects, and they removed one. Looks like I did a bad job of updating my blog post 😬

**Comment by ooade** [comment]
Hahaha. I literally didn't know about the mutationEffect hook. Glad it was removed :sweat_smile:
