### ISSUE TITLE
Broken links

### ISSUE THREAD

**Issue by eli8levit** [kentcdodds/old-kentcdodds.com#110]
I've noticed that you have some broken links that point to your post on Medium which doesn't exist anymore.
For example in [Application State Management post](https://kentcdodds.com/blog/application-state-management): 
<img width="744" alt="Screenshot 2019-03-24 at 22 11 06" src="https://user-images.githubusercontent.com/31045769/54885151-dacb1200-4e81-11e9-99b5-39b365e42377.png">
that points to `https://medium.com/dailyjs/reacts-%EF%B8%8F-new-context-api-70c9fe01596b`.
Do you want me to PR with fixed links (4 more places)?

**Comment by kentcdodds** [comment]
Yes please!

**Comment by eli8levit** [comment]
#111

**Comment by kentcdodds** [comment]
Thanks!
