### ISSUE TITLE
Highlighted lines in code snippets don't take full width

### ISSUE THREAD

**Issue by dimitrisnl** [kentcdodds/old-kentcdodds.com#115]
The problem arises when there is a scrollbar present. More [here](https://www.gatsbyjs.org/packages/gatsby-remark-prismjs/#optional-add-line-highlighting-styles)

>  However, you will notice that when a highlighted line runs wider than the surrounding code block container (causing a horizontal scrollbar), its background won’t be drawn for the initially hidden, overflowing part. :(

![Screen Shot 2019-03-26 at 2 38 39 PM](https://user-images.githubusercontent.com/4951004/54997791-30640380-4fd5-11e9-9425-4e2b2002cd7f.png)

_This website isn't using `gatsby-remark-prismjs` but the problem is similar_

**Comment by kentcdodds** [comment]
Hey, thanks! Would you like to submit a fix? 😄 https://github.com/kentcdodds/kentcdodds.com/blob/86b153136d485c604913e45f93a8f119b40021fb/src/components/layout.js#L116-L121

**Comment by dimitrisnl** [comment]
Sure, can try.

Edit: Although the changes should be done here 

https://github.com/kentcdodds/kentcdodds.com/blob/86b153136d485c604913e45f93a8f119b40021fb/src/components/mdx/code.js#L34-L36

Since we don't want `pre` to wrap but have a wrapper element do it.
