### ISSUE TITLE
How is this implemented?

### ISSUE THREAD

**Issue by spences10** [kentcdodds/old-kentcdodds.com#117]
It's not an issue, but I'd like to know how you use the fragment from [here]

To ue here:

https://github.com/kentcdodds/kentcdodds.com/blob/b5249808fca44281a3596310f2595a97cb0805d5/src/pages/index.js#L311-L317

[here]: https://github.com/kentcdodds/kentcdodds.com/blob/2e9fc256e3ce46b87c8d8424e73953cc4aba39b7/src/lib/fragments.js

It's puzzling me how you get the fragments to 'load' and then use them in the index page, tell me @kentcdodds can you use the `childImageSharp { ... }` in the GraphiQL Gatsby explorer?

**Comment by kentcdodds** [comment]
It's because this: https://github.com/gatsbyjs/gatsby/issues/11638#issuecomment-461643378

And it's pretty confusing.

> can you use the childImageSharp { ... } in the GraphiQL Gatsby explorer?

No, I don't think that I can 😞
