### ISSUE TITLE
Not able to deploy this fork on netlify, but you have active depl

### ISSUE THREAD

**Issue by asharamseervi** [kentcdodds/old-kentcdodds.com#161]
Hello Sir, I am learning with you, and found your blog is enhanced fork of [eggheadio starter](https://github.com/eggheadio/gatsby-starter-egghead-blog). I'm so inspired by this. As I'm learning, I want to write some articles with the forked version & deploy it over netlify. I tried to deploy with the minimal version(removing many unwanted things) as well as with original source code. 

Unfortunately, I never able to succeed with deployment over netlify, no matter how many times I refactored it and tried again. Might, I'm missing something either some important stuff or may be some credentials in `.env` or `.netlify` file, or something else.

Can you please help me to make lite version of blog, lite not as eggheadio starter but as enriched as your blog with less dependencies, so everyone from us can deploy their blog easily.

**Comment by kentcdodds** [comment]
Hi @asharamseervi,

I'm afraid that I don't have time to do this. Keep working at it and remove the code you don't need and you'll get it eventually. Good luck!
