### ISSUE TITLE
Code samples don't wrap long lines, can't read

### ISSUE THREAD

**Issue by pandaiolo** [kentcdodds/old-kentcdodds.com#164]
<img width="772" alt="Screenshot 2019-05-21 at 16 03 11" src="https://user-images.githubusercontent.com/1933404/58107644-2714a300-7be2-11e9-85fd-46a8ed575204.png">

The code blocks have a max width and don't wrap. Something is missing like `white-space: pre-wrap;` or code samples with lines already wrapped down to the mobile breakpoint. Not sure of the solution, just wanted to mention that readability issue. (especially for those without easy horizontal scrolling device like myself today)

Other than that, thanks for the great content, I'm always happy to read your new stuff  👍

**Comment by kentcdodds** [comment]
Thanks @pandaiolo,

I don't want to wrap the code as I think that would make it harder to read, however I've expanded the code blocks width a bit and for that specific blog post code snippet I made one of the comments multi-line so it fits better. Thanks!
