### ISSUE TITLE
Extract 'remark-embedder' plugin into it's own package

### ISSUE THREAD

**Issue by MichaelDeBoey** [kentcdodds/old-kentcdodds.com#172]
I was wondering if you're willing to extract the `remark-embedder` plugin into it's own package, so this could be used in other projects without just  copy-pasting the files?

**Comment by kentcdodds** [comment]
I plan to eventually, but I haven't had the time recently.

**Comment by MichaelDeBoey** [comment]
Would be awesome to see this happening 🙂

**Comment by MichaelDeBoey** [comment]
@kentcdodds Is there something I can do to help  you out  with this one? 🤔

Kinda "need" this one for codesandbox/codesandbox-client#2011

**Comment by kentcdodds** [comment]
If you'd like to open source it yourself that's welcome :) Please do credit me for the original idea. Also my hope is that there could be built-in embedders (like twitter/youtube/etc.) but users could also specify their own as well.

**Comment by MichaelDeBoey** [comment]
Nah I can wait 🙂
The reason I said "needed" (in quotes) is because I just wanted a heads up and offer my help 😉

Also don't have the time atm to figure this out how to setup the project properly

**Comment by MichaelDeBoey** [comment]
@kentcdodds Is this one on the roadmap yet? 🤔

**Comment by kentcdodds** [comment]
Sorry, it's just not a priority for me right now.

**Comment by MichaelDeBoey** [comment]
No problem.

Are there some resources I can read/watch and/or some boilerplate I can use to publish this one myself?

Would be happy to do that and make a PR here to use the new package. 🙂

**Comment by kentcdodds** [comment]
https://kcd.im/write-oss 😄

**Comment by MichaelDeBoey** [comment]
[`gatsby-remark-embedder`](https://github.com/MichaelDeBoey/gatsby-remark-embedder) is [released](https://github.com/MichaelDeBoey/gatsby-remark-embedder/releases/tag/v1.0.0) 🎉🎉🎉

PR is on it's way 😉
