### ISSUE TITLE
Bug? Link Intermittenly Points to Wrong URL

### ISSUE THREAD

**Issue by jsjoeio** [kentcdodds/old-kentcdodds.com#189]
### Problem:

Sometimes when this [blog post](https://kentcdodds.com/blog/what-open-source-project-should-i-contribute-to) loads, the link points to https://firstpr.me/#kentcdodds

Other times when it loads, it points to [https://egghead.io/courses/how-to-write-an-open-source-javascript-library](https://egghead.io/series/how-to-write-an-open-source-javascript-library). 

Guessing this is unintended behavior?

I was going to submit a PR to fix it but in the actual `index.md` file, you have the correct link so I'm not sure what's going on 🤷🏼‍♂️
 
<img width="1114" alt="image" src="https://user-images.githubusercontent.com/3806031/58898953-9b564880-86b0-11e9-8645-d92dd63348a5.png">

### Context

I opened the post in Firefox Developer Edition from your newsletter. Same thing happens in Chrome: http://recordit.co/EkrbLUOs6x

**Comment by kentcdodds** [comment]
I was able to reproduce it but I have no idea what's going on. I did a hard refresh and now I cannot reproduce it so I think we'll just hope this isn't a long term problem 🤞 

Thanks @jsjoeio!

**Comment by kentcdodds** [comment]
I reproduced it again. My guess is that this is a gatsby issue, so if someone from the gatsby team wants to investigate that would be super, but I don't have the bandwidth to look into it and I'll just hope that it's fixed magically in the future.

cc @jlengstorf
