### ISSUE TITLE
Line numbers are getting copied along with the code

### ISSUE THREAD

**Issue by hoodwink73** [kentcdodds/old-kentcdodds.com#198]
Heyya Kent

You have killing it lately. I have read your latest five articles. They all have been very relevant to me.

I think you maybe already aware of this but I just wanted to file an issue if you would like to prioritise it.

Good day, friend. Enjoy your workshops and your time away from twitter.

**Comment by krunalcodes** [comment]
it's working fine for me on chrome. which browser you are using?

**Comment by hoodwink73** [comment]
I am using Safari. But tested on Chrome too earlier.

Looks like CodeSandbox fixed it. 
Thanks for the ping, Closing the issue.
