### ISSUE TITLE
404

### ISSUE THREAD

**Issue by martellaj** [kentcdodds/old-kentcdodds.com#2]
Hitting kentcdodds.com gives me a 404.

**Comment by kentcdodds** [comment]
Alrighty, I think I've got it working. I'm now just using my domain registrar's DNS with netlify's hosting and free SSL for custom domains. Works pretty well.

Wish I didn't have to use Node 4 on netlify :-( also I need to figure out how to ignore certain files/directories with netlify... But it works great :) Thanks!
