### ISSUE TITLE
Upgrade `gatsby-mdx` to `gatsby-plugin-mdx`?

### ISSUE THREAD

**Issue by karlhorky** [kentcdodds/old-kentcdodds.com#222]
Hi Kent! Are you open to upgrading from `gatsby-mdx` to [the new `gatsby-plugin-mdx`](https://github.com/gatsbyjs/gatsby/tree/master/packages/gatsby-plugin-mdx), since it has been merged into the Gatsby repo?

More info: https://github.com/gatsbyjs/gatsby/pull/15559

**Comment by kentcdodds** [comment]
Absolutely. Want to make a pull request?

**Comment by MichaelDeBoey** [comment]
This can be closed since 59e76d6 I think? 🤔

**Comment by kentcdodds** [comment]
Thanks
