### ISSUE TITLE
CTAs showing obsolete workshop info

### ISSUE THREAD

**Issue by tamouse** [kentcdodds/old-kentcdodds.com#226]
I was reading "Avoid the Test User" tonight, and noticed that there were pop-up links / CTAs that are for workshops that are out of date:

![Avoid the Test User 2019-07-20 22-24-05(2)](https://user-images.githubusercontent.com/363583/61586581-7709da80-ab3d-11e9-96ea-a737a46df3e9.jpg)

![Avoid the Test User 2019-07-20 22-26-06(1)](https://user-images.githubusercontent.com/363583/61586584-7bce8e80-ab3d-11e9-85a6-0f28bb607180.jpg)

**Comment by tamouse** [comment]
p.s. -- I'm noticing these on the web site in general.

**Comment by kentcdodds** [comment]
Thanks, I'll get this fixed.
