### ISSUE TITLE
Lazy-load gatsby-remark-images?

### ISSUE THREAD

**Issue by karlhorky** [kentcdodds/old-kentcdodds.com#230]
What do you think of lazy-loading the images from blog posts ([example](https://kentcdodds.com/blog/advanced-react-component-patterns)) loaded with `gatsby-remark-images`?

One option would be [gatsby-remark-lazy-load](https://www.npmjs.com/package/gatsby-remark-lazy-load) by @1kohei1 (until gatsbyjs/gatsby#15716)

Ref: https://github.com/gatsbyjs/gatsby/issues/2288#issuecomment-483070110
Ref: https://github.com/gatsbyjs/gatsby/issues/15716

**Comment by JacobMGEvans** [comment]
Is this similar to #581? If it is it would be a good enhancement 😄

**Comment by kentcdodds** [comment]
Don't bother. I'm ditching Gatsby

**Comment by JacobMGEvans** [comment]
> Don't bother. I'm ditching Gatsby
