### ISSUE TITLE
/workshops page broken

### ISSUE THREAD

**Issue by LBWright** [kentcdodds/old-kentcdodds.com#267]
On Google Chrome and getting a blank page for workshops. It renders once and immediately goes white. This is the error I get in the console.

<img width="599" alt="Screen Shot 2019-08-27 at 8 04 21 AM" src="https://user-images.githubusercontent.com/36030324/63773684-4b4ae480-c8a1-11e9-8d61-76b538bd62a5.png">

**Comment by ericnkatz** [comment]
Was just about to tweet @kentcdodds about this too.

**Comment by ericnkatz** [comment]
Looks like it was related to date-fns update to 2.0 

https://github.com/kentcdodds/kentcdodds.com/commit/6c5b90310edd2704b16047b643b311dfbe3c4ef7#diff-b9cfc7f2cdf78a7f4b91a753d10865a2


relevant documentation: https://github.com/date-fns/date-fns/blob/master/docs/unicodeTokens.md

looks like just need to replace `YYYY` with `yyyy`.

**Comment by kentcdodds** [comment]
Thanks! I'm planning on fixing this soon, but if someone wants to make a pull request before me that's great. There are only two or three affected code locations I think.
