### ISSUE TITLE
Shawn Wangs podcast share card has the wrong text

### ISSUE THREAD

**Issue by theianjones** [kentcdodds/old-kentcdodds.com#275]
The title of Shawn Wang's podcast is "You Can Learn A Lot For The Low Price Of Your Ego - With Shawn Wang" but the share card looks like this:

![](https://raw.githubusercontent.com/kentcdodds/kentcdodds.com/master/content/podcast/01/12-shawn-wang/shawn-wang-card.png)

I don't think "Be intentional with your time" is the correct title here.

**Comment by kentcdodds** [comment]
cc @vojtaholik :)
