### ISSUE TITLE
Broken link in post — Write your own code transform

### ISSUE THREAD

**Issue by flexdinesh** [kentcdodds/old-kentcdodds.com#286]
Link to [existing macros](https://github.com/kentcdodds/babel-plugin-macros/blob/master/other/docs/macros.md) is broken in [Write your own code transform for fun and profit](https://kentcdodds.com/blog/write-your-own-code-transform) blog post.

I have learned so much about babel from the post. Thank you!

**Comment by kentcdodds** [comment]
Thanks!

@all-contributors please add @flexdinesh for bug
