### ISSUE TITLE
Images URL error: can not see images in publications

### ISSUE THREAD

**Issue by juandc** [kentcdodds/old-kentcdodds.com#31]
---
:memo: Post: '[When to use Control Props or State Reducers](https://kentcdodds.com/blog/control-props-vs-state-reducers)'
:file_folder: File: [`blog/control-props-vs-state-reducers/index.md`](https://github.com/kentcdodds/kentcdodds.com/blame/master/content/blog/control-props-vs-state-reducers/index.md)
:bug: Line: [#96](https://github.com/kentcdodds/kentcdodds.com/blame/master/content/blog/control-props-vs-state-reducers/index.md#L96)
---

:film_projector: Preview:

![image](https://user-images.githubusercontent.com/15987317/52684330-ea1a7f80-2f13-11e9-9f20-42fbf35a1104.png)

:computer: Code:

```
![gif of the rendered component showing an input and toggle that sync their state](./images/toggle1.gif)
```

:point_down:

![gif of the rendered component showing an input and toggle that sync their state](./images/toggle1.gif)

**Comment by juandc** [comment]
The GIF is okay directly in the [Github file](https://github.com/kentcdodds/kentcdodds.com/blob/master/content/blog/control-props-vs-state-reducers/index.md):

![image](https://user-images.githubusercontent.com/15987317/52684586-bee46000-2f14-11e9-9aa1-dad7c21a7102.png)

**Comment by kentcdodds** [comment]
Yeah, I noticed too 😬

Want to contribute a fix?

**Comment by juandc** [comment]
I'm not sure, sir. :disappointed_relieved:.

First time with Gatsby!
Looking at the code I think I can fix it, probably playing with the [gatsby-remark-relative-images](https://www.gatsbyjs.org/packages/gatsby-remark-relative-images/) plugin, but I don't know how much time would I need. Sorry about that :pray:.
The next time I'm going for it!

**Comment by kentcdodds** [comment]
It's fine. Just wanted to see if you were interested in making the change yourself. I'll get around to it eventually. Thanks for reporting it!

**Comment by kentcdodds** [comment]
This is fixed!

**Comment by kentcdodds** [comment]
@all-contributors please add @juandc for bug
