### ISSUE TITLE
Broken link in blog post

### ISSUE THREAD

**Issue by Crushford** [kentcdodds/old-kentcdodds.com#318]
Hey!
In [this blog post](https://github.com/kentcdodds/kentcdodds.com/blob/master/content/blog/semicolons-in-javascript-a-preference/index.md#transpilation-andor-uglification) you link to [Klye's blog post](http://blog.getify.com/not-all-semicolons), it doesn't exist there anymore and I can't find a new link for you.

Thanks!

**Comment by kentcdodds** [comment]
Thanks!

**Comment by kentcdodds** [comment]
@all-contributors please add @Crushford for bugs
