### ISSUE TITLE
Issue with understanding-reacts-key-prop

### ISSUE THREAD

**Issue by a-c-sreedhar-reddy** [kentcdodds/old-kentcdodds.com#329]
> For components, this means that React will run cleanup on effects (or componentWillUnmount), then it will run state initializers (or the constructor) and effect callbacks (or componentDidMount).

But effects do not work that way. First the new Component is rendered. Then  cleanup on old effects is done. Then new effects are run.

**Comment by kentcdodds** [comment]
Yeah, I'll clarify that wording a bit.
