### ISSUE TITLE
Feature Request: Date

### ISSUE THREAD

**Issue by chasm** [kentcdodds/old-kentcdodds.com#349]
It would be helpful if blog posts were publicly and clearly dated with publication date and last modified so that readers can tell how current the information is. Given the wealth of obsolete (or plain wrong) information out there, knowing who to trust and what is the latest is vital.

**Comment by josephrexme** [comment]
I think this will be really nice as well. I noticed there's currently a `Last Updated Date` but it might help to have a created date as well. It helps to put a context to the relevance and value of the articles.

**Comment by kentcdodds** [comment]
If a post is no longer relevant, I'll make note of that. The last updated date is the best I'm going to do :) Thanks!
