### ISSUE TITLE
Bad link targets

### ISSUE THREAD

**Issue by haleyrc** [kentcdodds/old-kentcdodds.com#363]
On your decade in review post, in the Livestreaming section for 2019, the intro video and CodeSandbox links point to the wrong places (https://www.brandonsanderson.com/ and https://writingexcuses.com/ respectively). The hard refresh trick from #189 didn't help. Just a heads up!

**Comment by kentcdodds** [comment]
Hi @haleyrc,

As mentioned in #189, I think this is a gatsby issue and I don't have the bandwidth to figure it out. I just tried again and the links seem to be going to the right place, so I'm going to go ahead and close and pray there's no further issues.

Thanks!
