### ISSUE TITLE
Browser cache not clearing from kentcodds --- Question

### ISSUE THREAD

**Issue by teaglebuilt** [kentcdodds/old-kentcdodds.com#385]
I cloned your repo and looked around on localhost. Ever since i have had issues with clearing the cache in my browser that wants to load your assets. I have deleted your repo on my host machine and cleared my cache. yet when i run localhost. I still will see your favicon or styles load in my browser by default on localhost if not over ruled by another project.  Is there a known reason or similar experience with this?

**Comment by kentcdodds** [comment]
Hi @teaglebuilt,

Here's what you want to do:

![image](https://user-images.githubusercontent.com/1500684/74775796-aad3ec80-5253-11ea-8c00-da93474f239e.png)

Click that "Clear site data" button and that'll get it all out :)

Good luck!
