### ISSUE TITLE
thoughts on blogging frameworks?

### ISSUE THREAD

**Issue by gabrielcsapo** [kentcdodds/old-kentcdodds.com#4]
I see you are "rolling your own" blogging framework with simple react views and routes. Having you looked at gatsby, Metalsmith or Hexo? The setup is pretty extensive and not as expressive as what you are able to do with rolling your own, do you have any thoughts on how to fix this? I was talking to @vonbearshark about how if Jekyll was simply translated one to one to JS it would fit 99.9% of use cases.

**Comment by kentcdodds** [comment]
Mostly because I don't have enough time to work on my website and I'm not interested in improving it 🤷‍♂️ This is evidenced by the fact that I'm using medium for my blog: https://blog.kentcdodds.com

Also, I based this on what I built for https://javascriptair.com so it was pretty easy and fast.

**Comment by gabrielcsapo** [comment]
@kentcdodds makes sense, I was just wondering if you had a pattern that you would be willing to discuss for people who are wanting to roll their own and optimizing for real world scale like you understand.

**Comment by kentcdodds** [comment]
I don't really have a pattern. I wouldn't do this again to be honest. I think I might use something like this next time: https://github.com/nozzle/react-static Or just use next.js with the static export functionality. I don't have time to work on my own custom solution :wink:

**Comment by gabrielcsapo** [comment]
I was just interested since you were recently committing blogs to your website https://github.com/kentcdodds/kentcdodds.com/commit/63c3f6a5eae725743d364220edbcab30126003ea, apologies 🤷‍♂️.

**Comment by kentcdodds** [comment]
I only do that because it's an easy place to write drafts for my newsletter: http://kcd.im/news 👍
