### ISSUE TITLE
Blog link not updated in writing page

### ISSUE THREAD

**Issue by clementloridan** [kentcdodds/old-kentcdodds.com#411]
I just find a 404 page to try to go to blog from the writing page :

<img width="1406" alt="Capture d’écran 2020-03-28 à 20 12 51" src="https://user-images.githubusercontent.com/15263596/77829209-9ed02a00-7131-11ea-8357-0ddd46992932.png">

**Comment by kentcdodds** [comment]
Ah! Thank you for that. I kinda forgot about that 😅

Just fixed: https://github.com/kentcdodds/kentcdodds.com/commit/ed4bce33d0a76c86eccae58fe0cf00021533637e
