### ISSUE TITLE
Add linkable headings like in GitHub markdown flavour

### ISSUE THREAD

**Issue by unrevised6419** [kentcdodds/old-kentcdodds.com#415]
Would be nice to have links to every heading (or at least `h1` and `h2`) in a blog post page, so we can reference them easier.

Ex: https://github.com/kentcdodds/kentcdodds.com#contributors

Notes:
- https://github.com/gatsbyjs/gatsby/tree/master/packages/gatsby-plugin-mdx#mdxprovider
- https://github.com/kentcdodds/kentcdodds.com/blob/master/src/components/mdx/index.js#L12
- https://github.com/kentcdodds/kentcdodds.com/blob/master/src/components/mdx/title.js

**Comment by kentcdodds** [comment]
Agreed. I'm pretty sure all it'll take is a gatsby/remark plugin. Want to investigate that and [make a PR](http://makeapullrequest.com)?

**Comment by unrevised6419** [comment]
Don't have to much time right now, working on other OSS projects.  
This is a easy one. I'll come back after some time and check this, if will not be done already.

**Comment by unrevised6419** [comment]
https://www.gatsbyjs.org/packages/gatsby-remark-autolink-headers/

**Comment by unrevised6419** [comment]
It seems this was implemented.
