### ISSUE TITLE
iPhone 5/SE layout issues

### ISSUE THREAD

**Issue by abhishekjakhar** [kentcdodds/old-kentcdodds.com#453]
**Workshop Page iPhone 5/SE**

The workshop box is having minimum width which is breaking out the workshop page layout.

<img width="1280" alt="kent-workshop-2" src="https://user-images.githubusercontent.com/19193724/81476749-2761e000-9231-11ea-94fd-b81bf98652c7.png">

<img width="1280" alt="kent-workshop-1" src="https://user-images.githubusercontent.com/19193724/81476733-1618d380-9231-11ea-9056-9ebe5eecef63.png">

**Podcast Page iPhone 5/SE**

The podcast page needs padding tweak on small screen

<img width="1280" alt="kent-podcast" src="https://user-images.githubusercontent.com/19193724/81476724-09947b00-9231-11ea-8732-026da02ea652.png">

**Comment by abhishekjakhar** [comment]
@kentcdodds It needs a little bit of tweaking on small screens, should I pick this up?

**Comment by kentcdodds** [comment]
A pull request would be welcome 😁

**Comment by abhishekjakhar** [comment]
Cool, I am picking this up and will raise the PR today

**Comment by abhishekjakhar** [comment]
This has been fixed in https://github.com/kentcdodds/kentcdodds.com/pull/454, closing it.
