### ISSUE TITLE
Can't navigate to blog directly on chrome (android)

### ISSUE THREAD

**Issue by mwhnrt** [kentcdodds/old-kentcdodds.com#491]
Hey Kent,

when navigating directly to your blog (https://kentcdodds.com/blog/) the page does not load. 

Experienced on chrome on Android.

Might test it tomorrow on my desktop and update this issue.

Cheers,
Matthias

**Comment by JacobMGEvans** [comment]
Were you able to test on your desktop? 

Do you use any adblockers or HTTPS Everywhere?

**Comment by mwhnrt** [comment]
At that time: yes. I cross checked on desktop and verified on another mobile device. But now, months later, it is magically fixed.
