### ISSUE TITLE
Keyword Pages

### ISSUE THREAD

**Issue by kentcdodds** [kentcdodds/old-kentcdodds.com#50]
So people can find what they want to find better.

**Comment by juancuiule** [comment]
Hi @kentcdodds do you know if someone is working on this? I think that I can try to implement this weekend.

**Comment by kentcdodds** [comment]
Hi @juancuiule! That's super kind of you to offer. Thanks.

I'm actually considering doing something a little special with my blog and curation. I'll let you know if I want any help with it when I'm ready to make it happen. Thanks anyway!
