### ISSUE TITLE
Blog posts are in wrong order

### ISSUE THREAD

**Issue by onemen** [kentcdodds/old-kentcdodds.com#563]
Hello Kent, congratulations on Epic React

After match-sorter pr [#101](https://github.com/kentcdodds/match-sorter/pull/101)
Blog posts sorted when the page loads and when there is no search term.
This altered the previous behavior that show the latest posts on top.

Also I have noticed that every time the search filed is emptied, The Search component (in components/search/index.js) is renders twice, since you call setFilteredBlogPosts twice from React.useEffect.

As i understand the code, in the case search is empty you don't need to call ```getMatchSorterWorker.searchAndSort```

https://github.com/kentcdodds/kentcdodds.com/blob/a150758624d821886868a50fa3f94de887c0a77d/src/components/search/index.js#L186

**Comment by kentcdodds** [comment]
Ah! I noticed that and was going to look into it later 🤭

Yeah, that makes sense. Would you be interested in making a pull request to fix that?

**Comment by JacobMGEvans** [comment]
> Ah! I noticed that and was going to look into it later 🤭
> 
> Yeah, that makes sense. Would you be interested in making a pull request to fix that?

If they don't I will later, when adding to the Discord documentation.
