### ISSUE TITLE
Issue: Figcaption not styled in "rendering-a-function-with-react" article

### ISSUE THREAD

**Issue by dance2die** [kentcdodds/old-kentcdodds.com#65]
# 🐛 What?

`<figcaption />` texts are not styled

![figcaption not styled](https://user-images.githubusercontent.com/8465237/53387852-ca914700-3956-11e9-8d1d-aba9f1d2bccb.png)

# ➕ Additional Context

I didn't create a PR for this as I did for the `PR` #64 because this would require code transformation change.

# 📖 Articles
- **Source**: https://medium.com/@kentcdodds/rendering-a-function-with-react-ca3eaf0751e2
- **Destination**: https://kentcdodds.com/blog/rendering-a-function-with-react

**Comment by kentcdodds** [comment]
All the `<figcaption>` things should just be alt-text on the image `![this is alt text](./images/0.png)`. Would you be interested in helping move those over?

**Comment by dance2die** [comment]
> All the `<figcaption>` things should just be alt-text on the image `![this is alt text](./images/0.png)`. Would you be interested in helping move those over?

Would proving an image description like this 👉 `![I see what you did there](./images/0.gif)` would suffice for all figcaptioned image?


![example code](https://user-images.githubusercontent.com/8465237/53421786-3f42a080-39ac-11e9-8c78-967c854b3cb5.png)

**Comment by kentcdodds** [comment]
Yep. That was always my intention for the caption anyway. Medium didn't allow for alt-text so that's what I used instead.

**Comment by dance2die** [comment]
Should I **remove** `<figcaption>` as I provide only the `alt-text`? Or should I **leave** the `<figcaption>` as they are?

**Comment by dance2die** [comment]
Thanks 👍.
I will add missing `alt-text` for images

**Comment by kentcdodds** [comment]
Yeah, I really want the figcaption removed in favor of the alt text. Thanks!
