### ISSUE TITLE
did-you-know

### ISSUE THREAD

**Issue by ChrisWcs** [kentcdodds/old-kentcdodds.com#69]
404

This blog post is about mediums multiple claps feature.... As you are moving from Medium, not sure if you need this one, but totally your choice.

**Comment by kentcdodds** [comment]
Thank a bunch! Most of these 404s are are actually articles that I intentionally didn't move over, but forgot to remove from the list. I will need to update those entries in here to point to the medium version of those posts though! https://github.com/kentcdodds/kcd-blog-redirector/blob/master/_redirects

**Comment by kentcdodds** [comment]
This has been resolved and now https://blog.kentcdodds.com/3079d5aec43b redirects to the right place. Thanks!
