### ISSUE TITLE
404 blog post link

### ISSUE THREAD

**Issue by Exifers** [kentcdodds/old-kentcdodds.com#709]
This link [https://kentcdodds.com/blog/how-to-use-react-context-effectively/](https://kentcdodds.com/blog/how-to-use-react-context-effectively/) returns a "Not found" page despite the content exists [here](https://github.com/kentcdodds/kentcdodds.com/blob/main/content/blog/how-to-use-react-context-effectively/index.mdx).

**Comment by kentcdodds** [comment]
I've got some bad news and good news... :-/

**Comment by Aprillion** [comment]
Good news is that it works on https://kent.dev/blog/how-to-use-react-context-effectively ?

**Comment by kentcdodds** [comment]
Yep. Just don't tweet that yet 😁
