### ISSUE TITLE
Why not comments?

### ISSUE THREAD

**Issue by alexilyaev** [kentcdodds/old-kentcdodds.com#87]
Hey Kent,

I'm also starting a blog, and was wondering what's the pros/cons of adding comments?
Seeing you've decided not to add them (and  @gaearon as well on [overreacted.io](https://github.com/gaearon/overreacted.io)).
Is a Twitter thread really a better experience vs. in site comments or Disqus?

Asking here in case other people would be interested in this as well.
Thanks!

Related:  
https://github.com/gaearon/overreacted.io/issues/7

**Comment by kentcdodds** [comment]
I find that comments are often a huge time-sink and I don't have time to manage comments on my blog/reply to them/handle spam/etc. :)
