### ISSUE TITLE
List bullets render above the text

### ISSUE THREAD

**Issue by tuhlmann** [kentcdodds/old-kentcdodds.com#93]
There's a little oddity in your reset.js that renders list bullets in markdown documents above the list item if the text takes the full width:

![Snag_3d0c160](https://user-images.githubusercontent.com/407319/54179315-bbeb7980-4498-11e9-9559-69dd3c34b5e5.png)

Not sure if you want it that way, if not I solved it by changing the `list-style-position` in reset.js:

```
  ul, ol {
    list-style-position: outside;
    margin-left: 1em;
    font-size: ${typography.baseFontSize};
  }
```

Which renders:

![Snag_3d20133](https://user-images.githubusercontent.com/407319/54179380-eccbae80-4498-11e9-86c7-7ff9ebc92430.png)

**Comment by kentcdodds** [comment]
Hi @tuhlmann,

Where are you seeing this? I don't think I have a blog post that says "In this data protection declaration"

**Comment by tuhlmann** [comment]
@kentcdodds This is one of my own pages, I've based my Gatsby installation off of yours. That's basically an mdx page with a list item text that's longer than the line so that it has to break line.

**Comment by tuhlmann** [comment]
Update: There might be something else intervening. I tried a long line on the links.mdx page of your blog and the list items show nicely. I guess I screwed something up.

Sorry for the confusion, I'll close the issue.

**Comment by tuhlmann** [comment]
@kentcdodds Actually the problem does occur on your page, but only if a heading is involved:

On the `uses.mdx` page I change the text to:

```
- #### The green screen 
  is rolled around regular 2" PVC pipe with a smaller 1" at the
  bottom.
```

And this renders as:
![Snag_572a6c3](https://user-images.githubusercontent.com/407319/54342825-bed39f00-463d-11e9-8bfa-78de37fea68b.png)

I keep the issue closed as this is a very special case and I'm not sure if it should behave that way or not. Just added my info for completeness sake.

Thanks again,
Torsten.

**Comment by kentcdodds** [comment]
Ah, yeah, that's a mistake in the markdown. I'll look into it. Thanks!
